variable project_id {}
variable cloudsql_proxy_sa_key {}
variable zone {}
variable k8s_username {}
variable k8s_password {}
variable db_instance_connection_name {}
variable metabase_db_name {}
variable metabase_db_user {}
variable metabase_db_password {}